"""Dimension value exact-match node: resolves B-A2 (dimension value fuzzy-match problem)
Exactly match dimension values mentioned by the user from the Doris column_value_info table,
ensuring that WHERE conditions generated by the LLM use the values actually stored in the database.
"""
from langgraph.runtime import Runtime
from app.agent.context import DataAgentContext
from app.agent.state import DataAgentState
from app.core.log import logger


async def match_dimension_value(state: DataAgentState, runtime: Runtime[DataAgentContext]):
    writer = runtime.stream_writer
    writer({"stage": "Dimension Value Exact Match"})
    try:
        value_repo = runtime.context["value_doris_repository"]
        keywords = state.get("keywords", [])
        query = state.get("query", "")

        # Extract candidate dimension values from query and keywords
        candidates = set(keywords)
        # Also use the query itself as a candidate
        candidates.add(query)

        matched_values = []
        for kw in candidates:
            if not kw or len(kw) < 1:
                continue
            # Exact match: value LIKE '%kw%'
            results = await value_repo.search_exact(kw, limit=5)
            for r in results:
                matched_values.append({
                    "value": r.get("value", ""),
                    "column_id": r.get("column_id", ""),
                    "column_name": r.get("column_name", ""),
                    "table_id": r.get("table_id", ""),
                })

        # Deduplicate
        seen = set()
        unique = []
        for v in matched_values:
            key = f"{v['column_id']}.{v['value']}"
            if key not in seen:
                seen.add(key)
                unique.append(v)

        logger.info(f"Dimension value exact match: {len(unique)} matches")
        return {"matched_dimension_values": unique}
    except Exception as e:
        logger.error(f"Dimension value exact match error: {e}")
        return {"matched_dimension_values": []}
